version: '3'

services:
   front-end:
     build:
        context: front-end
        dockerfile: Dockerfile
     hostname: front
     networks:
       - frontend
     ports:
       - "3001:3000"
   back-end:
     build:
        context: back-end
        dockerfile: Dockerfile
     hostname: back
     networks:
       -frontend
       -backend
     ports:
       - "8080:8080"
   database:
     build:
        context: database
        dockerfile: Dockerfile
     hostname: database
     networks:
       -backend
     ports: 
       - "3306:3306"