version: '3'

services:
    front-end:
     build:
        context: front-end
        dockerfile: Dockerfile
     hostname: front
     ports:
       - "3001:3000"
   back-end:
     build:
        context: back-end
        dockerfile: Dockerfile
     hostname: back
     ports:
       - "8080:8080"
   mysql:
     image: mysql
     hostname: database
     environment:
       MYSQL_DATABASE: 'database'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'rootpasswor'
     ports: 
       - "3306:3306"